name: Post ai to Dev.to

on:
  push:
    branches:
      - main

jobs:
  post-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract ai metadata and content
        id: extract_ai
        run: |
          # Read TITLE from ai.md
          TITLE=$(awk -F': ' '/^title:/ {print $2}' ai.md | sed 's/"//g')
          # Read TAGS from ai.md and format as JSON array
          TAGS=$(awk -F': ' '/^tags:/ {print $2}' ai.md | sed 's/\[//g' | sed 's/\]//g' | sed 's/, /", "/g' | sed 's/^/["/' | sed 's/$/"]/')
          # Read PUBLISHED from ai.md
          PUBLISHED=$(awk -F': ' '/^published:/ {print $2}' ai.md)
          # Read BODY from ai.md excluding YAML front matter
          BODY=$(sed -n '/^---$/,/^---$/!p' ai.md | sed '1d' | sed '2d')

          echo "TITLE: $TITLE"
          echo "TAGS: $TAGS"
          echo "PUBLISHED: $PUBLISHED"
          echo "BODY: $BODY"

          echo "::set-output name=title::$TITLE"
          echo "::set-output name=tags::$TAGS"
          echo "::set-output name=published::$PUBLISHED"
          echo "::set-output name=body::$BODY"

      - name: Post ai to DEV.to
        env:
          API_KEY: ${{ secrets.DEV_TO_API_KEY }}
        run: |
          TITLE="${{ steps.extract_ai.outputs.title }}"
          TAGS="${{ steps.extract_ai.outputs.tags }}"
          PUBLISHED="${{ steps.extract_ai.outputs.published }}"
          BODY="${{ steps.extract_ai.outputs.body }}"

          echo "Posting ai to DEV.to..."
          echo "TITLE: $TITLE"
          echo "TAGS: $TAGS"
          echo "PUBLISHED: $PUBLISHED"
          echo "BODY: $BODY"

          curl -X POST -H "Content-Type: application/json" \
            -H "api-key: $API_KEY" \
            -d '{"ai":{"title":"'"$TITLE"'","body_markdown":"'"$BODY"'","published":'"$PUBLISHED"',"tags":'"$TAGS"'}}' \
            https://dev.to/api/ais