name: Post Article to Dev.to

on:
  push:
    branches:
      - main

jobs:
  post-article:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up curl environment
        run: |
          API_KEY="${{ secrets.DEV_TO_API_KEY }}"
          TITLE="Title"
          BODY="Body"
          TAGS='["discuss", "javascript"]'
          PUBLISHED=false

          curl -X POST -H "Content-Type: application/json" \
            -H "api-key: $API_KEY" \
            -d '{"article":{"title":"'"$TITLE"'","body_markdown":"'"$BODY"'","published":'"$PUBLISHED"',"tags":'"$TAGS"'}}' \
            https://dev.to/api/articles
