name: Publish to Dev.to

on:   
  push:
    paths:
      - 'posts/**/**.md'  # Path for community timeline
      - 'posts/**/**/**.md'  # Path for all posts (yearly)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4.1.6

    - name: Publish articles on dev.to
      continue-on-error: true
      uses: sinedied/publish-devto@v2
      with:
        files: 'posts/**/*.md'
        devto_key: ${{ secrets.DEV_TO_API_KEY }}
        github_token: ${{ secrets.TOKEN }}
        conventional_commits: true
